### PR TITLE
export theme context for class component consumption

### PR DESCRIPTION
**Pull request by mohsinulhaq**
Fixes https://github.com/Shopify/restyle/issues/79

### CODE REVIEW

**Comment by mohsinulhaq** [comment]
!CLA

**Comment by mohsinulhaq** [comment]
@JoelBesada looks good?

**Comment by mohsinulhaq** [comment]
@JoelBesada ?

**Comment by JoelBesada** [comment]
Yes, thanks! Sorry for the delay.

**Pull request merged**
